template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "mans1258"
__REPO__ = "lang-mns"
__UND2C__ = "mns"
__UNDEFINED__ = "Mansi"
__UND__ = "mns"
