template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "mans1258"
__REPO__ = "lang-mns"
__UND2C__ = "mns"
__UNDEFINED__ = "Mansi"
__UND__ = "mns"
