[package]
name = "mns"
human_name = "Mansi"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.mns]
filename = "mns-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-mns"
platform = "windows"
uuid = "F1EACD2F-9DEF-471A-BA7C-4C42560EEAA3"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.mns"
package = "speller-mns"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-mns-mso"
platform = "windows"
uuid = "9A7E85AB-B1A1-4471-8DC5-EB6152F45DE6"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-mns"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
